title: August Tollerup
description: Bookmark this to keep an eye on my project updates!
lsi: false
safe: true
source: 4ug-aug.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
