title: August Tollerup
description: Bookmark this to keep an eye on my project updates!
theme: jekyll-theme-minima
lsi: false
safe: true
source: 4ug-aug.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Navigation
header_pages:
  - about.md
  - blog.md
  - projects.md

# Defaults
defaults:
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
